- name: Install and Configure Carbon Black
  hosts: all
  become: yes
  vars:
    cb_license_key: "YOUR_LICENSE_KEY_HERE"
    cb_installer_url: "https://example.com/carbon-black-installer.rpm"  # Replace with actual URL
    cb_service_name: "cbdaemon"

  tasks:
  
    # ============================
    # INSTALLATION
    # ============================
    - block:
        - name: Download Carbon Black installer
          get_url:
            url: "{{ cb_installer_url }}"
            dest: /tmp/carbon-black-installer.rpm
            mode: '0755'

        - name: Install Carbon Black
          command: rpm -ivh /tmp/carbon-black-installer.rpm
          args:
            creates: /opt/carbonblack/cbdaemon  # Prevents re-installation

      rescue:
        - name: Log installation failure
          debug:
            msg: "Carbon Black installation failed on {{ inventory_hostname }}"

        - name: Fail the playbook if installation fails
          fail:
            msg: "Critical error: Carbon Black installation failed!"

    # ============================
    # LICENSE CONFIGURATION
    # ============================
    - block:
        - name: Register Carbon Black with the license key
          command: "/opt/carbonblack/bin/cbdaemon --register {{ cb_license_key }}"
          register: registration_status
          failed_when: "'Error' in registration_status.stdout"

      rescue:
        - name: Log registration failure
          debug:
            msg: "License registration failed on {{ inventory_hostname }}"

        - name: Fail the playbook if registration fails
          fail:
            msg: "Critical error: License registration failed!"

    # ============================
    # SERVICE VERIFICATION
    # ============================
    - name: Ensure Carbon Black service is running
      systemd:
        name: "{{ cb_service_name }}"
        state: started
        enabled: yes

    - name: Verify Carbon Black service status
      command: systemctl is-active "{{ cb_service_name }}"
      register: cb_service_status
      failed_when: cb_service_status.stdout != "active"

    - name: Report successful installation
      debug:
        msg: "Carbon Black successfully installed and configured on {{ inventory_hostname }}"
